import { FC, ReactNode } from 'react'
import 'app/globals.css'

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

interface Props {
	children: ReactNode
}

const RootLayout: FC<Props> = ({ children }) => {
	return (
		<html lang="en">
			<body>
				<header>header</header>
				{children}
				<footer>footer</footer>
			</body>
		</html>
	)
}

export default RootLayout
